---
title: "BRIN 2023 saham BRIS"
author: "Akbar Arta"
date: "4/17/2023"
output: html_document
---

```{r}
library(ggplot2)
library(tidyverse)
library(tidyr)
library(forecast)
library(TSstudio)
library(plotly)
```
```{r}
data<-read.csv(file.choose(),header=T,sep=";",dec=",")
head(data)
dim(data)
attach(data)
```
```{r}
#Membagi data training dan tees
trans <- as.ts(data$Close)
datatrain <- subset(trans, start = 1, end =47 )
datates <- subset(trans, start = 48, end =59 )
```
```{r}
#partisi data train dam data tes
plot(data$Close,
     main = "Partition Training Data and Test Data",
     ylab = "Harga", xlab="Time",
     type='l', col='blue', las=1)

abline(v=47, lty=2)

text(10, 2500, "Training Data",col="red")
text(55, 2500, "Test Data",col="yellow")
```

```{r}
## Transformasi data time series
trans <- as.ts(data$Close)
series=ts(trans, start=c(2018,07,01), frequency=12)
(series)
```
```{r}
decompose(series) %>%
  autoplot()
```
```{r}
#Double Exponential
model.1 <- HoltWinters(series, gamma=F)
model.1
```
```{r}
prediksi<- forecast(object = model.1, h = 48)
prediksi
```
```{r}
train <- series %>% head(-11)
test <- series %>% tail(11)
autoplot(prediksi)+autolayer(test)
```
```{r}
accuracy(model.1$fitted[,1], train)
accuracy(model.1$fitted[,1], test)
```
```{r}
##PLOT PERAMALAN
fce=forecast(model.1,h = 48)
fce
plot(fce, main="BRIS Stock Forecasting Using DES")
```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
```{r}

```
