---
title: "Forecasting BRIS Stock with ARIMA Method"
author: "Akbar Arta"
date: "4/16/2023"
output: html_document
---

```{r}
library(forecast)
library(FitAR)
library(lmtest)
library(tseries)
library(psych)
library(ggplot2)
library(heatmaply)
library(visdat)
library(reshape2)
library(tidyr)
library(DataExplorer)
library(normtest)
```
```{r}
## Data
data<-read.csv(file.choose(),header=T,sep=";",dec=",")
head(data)
dim(data)
attach(data)
```
```{r}
#DATA PREPROCESSING
##Dimensi data
dim(data)
```
```{r}
##Variabel pada dataser
names(data)
str(data)
```
```{r}
##Cek missing data
sapply(data, function(x) sum(is.na(x)))
```
```{r}
##Melihat statistik data
summary(data)
hist(data$Close, main ="Saham BRIS", xlab="Harga")
shapiro.test((data$Close))
```
```{r}
#Membagi data training dan tees
trans <- as.ts(data$Close)
datatrain <- subset(trans, start = 1, end =47 )
datates <- subset(trans, start = 48, end =59 )
```
```{r}
#partisi data train dam data tes
plot(data$Close,
     main = "Partition Training Data and Test Data",
     ylab = "Harga", xlab="Time",
     type='l', col='blue', las=1)

abline(v=47, lty=2)

text(10, 2500, "Training Data",col="red")
text(55, 2500, "Test Data",col="yellow")
```
```{r}
## Transformasi data time series
series=ts(datatrain, start=c(2018,07,01), frequency=12)
series
```
```{r}
## lihat plot buat gambaran
ts.plot(series,ylab="Value",main="The Plot of BRIS Stock before Differentencing",col="turquoise",lwd=2)
legend("bottomright",c("Value"),cex=0.8,lty=5,text.font=2,col=c("turquoise"))
```
```{r}
## Melihat plot ACF PACF sebelum differencing
ggAcf(series,lag.max=100)+ ggtitle("The Plot of ACF before Differencing")

#terlihat sinusaidal
ggPacf(series,lag.max=100)+ ggtitle("The Plot of PACF before Differencing")
```

```{r}
## Stasioner Rata-Rata
#H0 = tidak stasioner, alternative hypothesis = H1 = stasioner
#pvalue > alfa maka h0 diterima (tidak stasioner dlm rata2)
adf.test(series)
```
```{r}
## Differencing 1 kali
df.series=diff(series, 1)
# Cek Stasioner Rata-Rata
adf.test(df.series) #OK

## Differencing 2 kali
df.series1=diff(df.series, 1)
# Cek Stasioner Rata-Rata
adf.test(df.series1) #OK
```
```{r}

## Lihat plot data lagi
ts.plot(df.series1,ylab="Value",main="The Plot of BRIS Stock after Differentencing",col="turquoise",lwd=2)
legend("bottomright",c("Value"),cex=0.8,lty=5,text.font=2,col=c("turquoise"))

```
```{r}
## Identifikasi model dengan ACF PACF
ggAcf(df.series1)+ ggtitle("The Plot of ACF BRIS Stock")
ggPacf(df.series1)+ ggtitle("The Plot of PACF BRIS Stock")
```
```{r}
# CATATAN: q cutoff ACF, p cutoff PACF. (p,d,q)
## IMA(q) q = 3, diff = 2, 3
model1=arima(series,order=c(0,2,0))
model2=arima(series,order=c(1,2,0))
model3=arima(series,order=c(2,2,0))
model4=arima(series,order=c(3,2,0))
model5=arima(series,order=c(0,2,1))
model6=arima(series,order=c(1,2,1))
model7=arima(series,order=c(2,2,1))
model8=arima(series,order=c(3,2,1))
model9=arima(series,order=c(0,2,2))
model10=arima(series,order=c(1,2,2))
model11=arima(series,order=c(2,2,2))
model12=arima(series,order=c(3,2,2))
model13=arima(series,order=c(0,2,3))
model14=arima(series,order=c(1,2,3))
model15=arima(series,order=c(2,2,3))
model16=arima(series,order=c(3,2,3))
```
```{r}
#untuk menampilkan p-value pada uji signifikansi parameter
#coeftest(model1) 
coeftest(model2) #
coeftest(model3)
coeftest(model4) 
coeftest(model5) #
coeftest(model6)
coeftest(model7) 
coeftest(model8) 
coeftest(model9)
coeftest(model10) 
coeftest(model11) 
coeftest(model12)
coeftest(model13) 
coeftest(model14) 
coeftest(model15) #
coeftest(model16)
```
```{r}
list(AIC(model2), AIC(model5), AIC(model15))
```
```{r}
summary(model15)
```
```{r}
#Diagnostik Model (Uji Asumsi)
#RESIDUAL -----------
r2=residuals(model15)

#=====Uji Normalitas Data======
n2=length(r2) #jumlah
mean2=mean(r2) #rata2
sd2=sd(r2) #standar deviasi
res2=rnorm(n2,mean2,sd2)
cek.normalitas=ks.test(r2,res2)
cek.normalitas
```
```{r}
#=====Uji White Noise-Autokorelasi=====
cek.WNA=Box.test(r2,lag=1,type=c("Ljung-Box")) ; cek.WNA
```
```{r}
#=====Uji White Noise-Heteroskedastisitas=====
h2=r2^2
cek.heteros=Box.test(h2,lag=1,type=c("Ljung-Box")) ;
cek.heteros
```
```{r}
ramalan_arima223 <- forecast::forecast(datatrain,model=model15, h=48)
accuracy(ramalan_arima223, datates)
```
```{r}
##----FORECAST
peramalan=predict(model15,n.ahead=48)$pred
peramalan
```
```{r}
##Prediksi

full <- predict(model15,n.ahead = 48)$pred
hasilforcasting <- as.data.frame(full)
hasilforcasting

##PLOT PERAMALAN
fc=forecast(model15,h = 48)
fc
plot(fc, main="BRIS Stock Forecasting Using ARIMA")

```

```{r}

```